### ISSUE TITLE
The Y coordinate seemed to show not the frequency, but the amplitude

### ISSUE THREAD

**Issue by cddqssc** [orchidas/Pitch-Tracking#3]
I tested it and found that the Y coordinate seemed to show not the frequency, but the amplitude.With the increase of input voice frequency, the data of x-axis becomes more dense, while the y-axis does not change:
![image](https://user-images.githubusercontent.com/31430047/166087952-c882496f-40f9-4506-bdfe-1f752df0ec46.png)

**Comment by orchidas** [comment]
Thanks for using the plugin. Can you please share the voice file you are testing on? I am certain the y-axis shows the pitch plot, but it is possible that it is detecting the pitch incorrectly. I have not tested the detector on speech, but it works fine on singing samples, since the pitch does not change very rapidly.

**Comment by cddqssc** [comment]
Thank you for your reply. I checked the code carefully again. There was something wrong with some of the codes I modified. After I modified them back, everything worked well. Thank you for providing such a good plug-in.
